spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/mydatabase
    password: Password@123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  application:
    name: demo.project
pii-encryption:
  key: ${PII_ENCRYPTION_KEY:6v3TyEgjUcQRnWuIhjdTzq==}
  version: ${PII_ENCRYPTION_VERSION:v1}
